#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     uSonic,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rack,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     pulley,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    basket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//
//
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	//servo[goalHook] = 0;

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void stopDrive(int wait)
{
	motor[right] = 0;
	motor[left] = 0;
	wait10Msec(wait);
}
void driveForward(int wait)
{
	motor[left] = 100;
  	motor[right] = 100;
  	wait10Msec(wait);
  	stopDrive(5);
}
void driveBackward(int wait)
{
	motor[left] = -100;
  	motor[right] = -100;
  	wait10Msec(wait);
 	stopDrive(5);
}
void turnLeftFast(int wait)
{
	motor[left] = 100;
	motor[right] = -100;
	wait10Msec(wait);
	stopDrive(5);
}
void turnRightFast(int wait)
{
	motor[right] = 100;
	motor[left] = -100;
	wait10Msec(wait);
	stopDrive(5);
}
void shiRight(int i)
{
	for(int j = 0; j < i; j++)
	{
		turnRightFast(10);
		stopDrive(3);
		driveForward(8);
		stopDrive(3);
	}
}
void shiLeft(int i)
{
	for(int j = 0; j < i; j++)
	{
		turnLeftFast(15);
		stopDrive(3);
		driveBackward(8);
		stopDrive(3);
	}
}
task main()
{
	initializeRobot();
	waitForStart(); // Wait for the beginning of autonomous phase.
  	//Robot goes down ramp , just past the tape
  //starting();
  int dist = SensorValue[uSonic];
	int dir = SensorValue[irSensor];
	driveBackward(155);
	wait10Msec(20);
	turnLeftFast(105);
}
