#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     uSonic,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
int threshold=  15;
	while(true)
	{
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) > threshold || abs(joystick.joy1_y2) > threshold)
	    {
	     	motor[left] = joystick.joy1_y1;
	     	motor[right] = joystick.joy1_y2;
	    }
	  else
		  {
		  	motor[left] = 0;
		  	motor[right] = 0;
		  }
		nxtDisplayCenteredBigTextLine(1, "Dir=%d", SensorValue[irSensor]);
		nxtDisplayString(2, "Dir=%d", SensorValue[uSonic]);
		int dir = SensorValue[irSensor];
		wait1Msec(3);
	}
}
