#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    hook,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Joystick is included in this program

task main()
{
  while(true) //infinite loop
  {
    getJoystickSettings(joystick); //retrieves data from the joystick
    //Left joystick
    //forward and back
    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[left] = joystick.joy1_y1;
      motor[right] = joystick.joy1_y1;
    }
    // Right joystick turns
    // turn right
    else if(joystick.joy1_x2 > threshold)
    {
      motor[left] = joystick.joy1_x2;
      motor[right] = -joystick.joy1_x2;
    }
    // turn left
    else if (joystick.joy1_x2 < negthreshold)
    {
      motor[right] = abs(joystick.joy1_x2);
      motor[left] = joystick.joy1_x2;
    }
    // Otherwise do not move
    if(joy1Btn(4))
    {
    	servo[hook] = 0;
    }
    if(joy1Btn(2))
  	{
    	servo[hook] = 255;
  	}
  }
}
