#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rack,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     pulley,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     basket,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
	int threshold = 15;
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy1Btn(1)) //X
		{
			motor[right] = joystick.joy1_y1;
		}
		if(joy1Btn(2)) //A
		{
			motor[left] = joystick.joy1_y1;
		}
		if(joy1Btn(3)) //B
		{
			motor[rack] = joystick.joy1_y1;
		}
		if(joy1Btn(4)) //Y
		{
			motor[pulley] = joystick.joy1_y1;
		}
		if(joy1Btn(5)) //Y
		{
			motor[basket] = joystick.joy1_y1;
		}
		if(abs(joystick.joy1_y1) < threshold)
		{
			motor[right] = 0;
			motor[left] = 0;
			motor[rack] = 0;
			motor[pulley] = 0;
			motor[basket] = 0;
		}
		nxtDisplayCenteredBigTextLine(1, "Dir=%d", SensorValue[irSensor]);
		wait1Msec(3);
	}
}
