#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     barrel,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     pulley,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    goalHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Ramp Autonomous w/o sensors
//
// This autonomous code is meant for when we start on the ramp and with no sensors.
// The robot will go down the ramp
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	servo[goalHook] = 0;

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void driveForward(int wait)
{
	motor[left] = 100;
  motor[right] = 100;
  wait10Msec(wait);
  motor[left] = 0;
  motor[right] = 0;
}
void driveBackward(int wait)
{
	motor[left] = -100;
  motor[right] = -100;
  wait10Msec(wait);
  motor[left] = 0;
  motor[right] = 0;
}
void turnRightFast(int wait)
{
	motor[left] = 100;
	wait10Msec(wait);
	motor[left] = 0;
}
void turnRightSlow(int wait)
{
	motor[left] = 75;
  wait10Msec(wait);
  motor[left] = 0;
}
void turnLeftFast(int wait)
{
	motor[right] = 100;
	wait10Msec(wait);
	motor[right] = 0;
}
void turnLeftSlow(int wait)
{
	motor[right] = 75;
  wait10Msec(wait);
  motor[right] = 0;
}
void tankTurnRight(int wait)
{
	motor[left] = 100;
	motor[right] = -100;
	wait10Msec(wait);
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  driveBackward(100);
	servo[goalHook] = 128;
	// The robot stops and hooks onto the tube.
	turnRightSlow(20);
	driveForward(100);
	// The robot aligns itself to go toward the parking zone
	tankTurnRight(100);
	servo[goalHook] = 0;
	// The robot turns around and drops off the rolling goal
	driveForward(100);
	// The robot returns to the area where the rolling goals
	tankTurnRight(100);
	servo[goalHook] = 128;
	// The robot turns around to retireve another rolling goal
	driveForward(100);
	tankTurnRight(100);
	servo[goalHook] = 0;
	// The robot gets back to the parking zone and turns around to drop off the goal
	driveForward(100);
	// The robot leaves the parking zones
}
