#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    hook,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Joystick is included in this program

task main()
{
  while(true) //infinite loop
  {
  	getJoystickSettings(joystick);
    if(joy1Btn(1)) //close
    {
    //servo[hook] = 180; //l
    //servo[hook2] = 30; //r

    servo[hook] = abs(joystick.joy1_y1) * 2;
    }
    else if(joy1Btn(2)) //open
    {
	    //servo[hook2] = 180;
 		  //servo[hook] = 120;
    	servo[hook] = abs(joystick.joy1_y1) * 2;
    }
    else if(joy1Btn(3)) //good close
    {
     servo[hook2] = abs(joystick.joy1_y1) * 2;
    }
    nxtDisplayCenteredBigTextLine(1, "Dir=%d", ServoValue[hook]);
		nxtDisplayString(2, "Dir=%d", ServoValue[hook2]);

    /*else if(joy1Btn(3))
    {
    	servo[basket] = 250; //in contact
    }
    else if(joy1Btn(4))
    {
    	servo[basket] = 100;
	}*/
    wait10Msec(5);
  }
}
