#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     tusks,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Joystick is included in this program

task main()
{
  int negthreshold = -15;
  int threshold = 15; //to avoid unnecessary movement

  while(true) //infinite loop
  {
    getJoystickSettings(joystick); //retrieves data from the joystick
    if(abs(joystick.joy1_y1) > threshold) //the left joystick moves the robot forward and backward
    {
      motor[left] = joystick.joy1_y1;
      motor[right] = joystick.joy1_y1;
    }
    else if(joystick.joy1_x2 > threshold) //the right joystick controls the robot's turns
    {
      motor[left] = joystick.joy1_x2;
      motor[right] = -joystick.joy1_x2;
    }
    else if (joystick.joy1_x2 < negthreshold)
    {
      motor[right] = abs(joystick.joy1_x2);
      motor[left] = joystick.joy1_x2;
    }
    // Otherwise do not move
    else
  	{
  		motor[right] = 0;
  		motor[left] = 0;
  	}
    if(joy1Btn(4) == 1)
    {
    	motor[tusks] = 25;
    }
    else if(joy1Btn(2))
  	{
  		motor[tusks] = -25;
  	}
    else
	  {
	  	motor[tusks] = 0;
	  }

  }
}
